Update OxygenCheckWellFormedNess.yml

diff --git a/.github/workflows/OxygenCheckWellFormedNess.yml b/.github/workflows/OxygenCheckWellFormedNess.yml
--- a/.github/workflows/OxygenCheckWellFormedNess.yml
+++ b/.github/workflows/OxygenCheckWellFormedNess.yml
@@ -20,22 +20,25 @@ jobs:
       run: |
           cd scripts/oxygen/scripts
           ./validateCheckDITA.sh -i ../../../dita/rtc_api.xpr -r ditaValidationReport_cn.xml
+          
+          if [ $? -eq 0 ]
+            then
+              echo "Validation successful for cn DITA files"
+              exit 0
+            else
+              echo "Validation failure for cn DITA files"
+              echo ditaValidationReport_cn.xml
+              exit 1
+          fi
+          
           ./validateCheckDITA.sh -i ../../../en-US/dita/rtc_api.xpr -r ditaValidationReport_en.xml
-    - name: Upload cn validation report to release
-      uses: svenstaro/upload-release-action@v2
-      with:
-          repo_token: ${{ secrets.GITHUB_TOKEN }}
-          file: scripts/oxygen/scripts/ditaValidationReport_cn.xml
-          asset_name: ditaValidationReport_cn
-          tag: main
-          overwrite: true
-          body: "Comment release"
-    - name: Upload en validation report to release
-      uses: svenstaro/upload-release-action@v2
-      with:
-          repo_token: ${{ secrets.GITHUB_TOKEN }}
-          file: scripts/oxygen/scripts/ditaValidationReport_en.xml
-          asset_name: ditaValidationReport_en
-          tag: main
-          overwrite: true
-          body: "Comment release"          
+ 
+          if [ $? -eq 0 ]
+            then
+              echo "Validation successful for en DITA files"
+              exit 0
+            else
+              echo "Validation failure for en DITA files"
+              echo ditaValidationReport_en.xml
+              exit 1
+          fi
